name: freeorion-empanada
version: "0.4.8snap2"
summary: turn-based space empire and galactic conquest (4X) computer game
description: |
  FreeOrion is a free, open source, turn-based space empire and galactic
  conquest (4X) computer game being designed and built by the FreeOrion project.
  FreeOrion is inspired by the tradition of the Master of Orion games, but is
  not a clone or remake of that series or any other game.
grade: stable
confinement: strict

apps:
    freeorion-empanada:
        command: desktop-launch freeorion -S $SNAP_USER_COMMON/save # --resource-dir $SNAP/share/freeorion/default
        plugs: [home, pulseaudio, opengl, network, screen-inhibit-control, browser-support, x11]
        desktop: share/applications/freeorion.desktop
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/freeorion
            LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
parts:
    freeorion:
        source: https://github.com/freeorion/freeorion.git
        source-branch: release-v0.4.8
        #source-tag: v0.4.8
        source-type: git
        override-build: |
            sed -i.bak -e 's|Icon=freeorion$|Icon=${SNAP}/meta/gui/icon.png|g' ../src/freeorion.desktop
            snapcraftctl build
        plugin: cmake
        build-packages:
            - cmake
            - debhelper
            - dpkg-dev
            - libalut-dev
            - libboost-all-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libglew-dev
            - libglu1-mesa-dev
            - libjpeg-dev
            - libogg-dev
            - libopenal-dev
            - libpng-dev
            - libsdl2-dev
            - libtiff-dev
            - libvorbis-dev
            - pkg-config
            - python
        stage-packages:
            - mesa-utils
            - libgl1-mesa-dri
            - python
        after: [ desktop-gtk3 ]
